services:
  cashsharing:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: cashsharing
    ports:
      - "8081:8081"
    environment:
      CASH_SHARING_DATA: /data
      CASH_SHARING_SECRET: ASDFGHJKL
      CASH_SHARING_ADMIN_EMAIL: admin@example.com
      CASH_SHARING_ADMIN_PASSWORD: admin123
    volumes:
      - ./database:/data
    restart: unless-stopped