default_tags = [
    "General",
    "Flights",
    "Accommodation",
    "Transport",
    "Car Rental",
    "Fuel",
    "Dining Out",
    "Groceries",
    "Alcohol & Bars",
    "Coffee & Snacks",
    "Entertainment",
    "Tours & Excursions",
    "Attractions",
    "Adventure Activities",
    "Shopping",
    "Souvenirs & Gifts",
    "Clothing",
    "Travel Insurance",
    "Visa & Fees",
    "Tolls & Parking",
    "International Tax & Currency Exchange",
    "Internet & Communication",
    "Miscellaneous",
    "Insurance",
]